### ISSUE TITLE
Consider allowing unauthenticated read access to Android build artifacts -> Maven Central

### ISSUE THREAD

**Issue by ellenhp** [stadiamaps/ferrostar#139]
I tried to take a dependency on Ferrostar today and ran into an issue where I can only pull the package from the Maven repo if I authenticate with a GitHub personal access token. Is this intentional? I'm sure GitHub makes it way easier to push to their Maven repo from CI than pushing to Maven Central or something, but it would make adoption easier if there was an alternative that didn't require auth. As it stands I'm going to have to add "create a GitHub account" to our build instructions which isn't reasonable to expect of the general public, and I don't think "classic" auth tokens support scopes so I'm going to have to give the CI/CD pipeline read access to my entire account just to pull these artifacts in.

Background: see step 1 here https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-gradle-registry#using-a-published-package

**Comment by Archdoog** [comment]
GitHub's auth requirements for published packages are definitely annoying when it comes to a publicly available library like this. Our end goal is definitely to get it on maven central. We've been dragging our feet a bit on that one because of all the sonatype upgrades going on there.

Lots has changes since last I looked on the maven central website(s), so maybe now's a good time to re-evaluate. I'll make sure it's on our todo list to discuss next week in the ferrostar call.

**Comment by ellenhp** [comment]
Excellent! Thank you for taking a look at this :)

**Comment by ianthetechie** [comment]
Yes! Thanks for your feedback @ellenhp. This is indeed on our TODO list. It's just a surprisingly bureaucratic process to get a MavenCentral account so I put it off 😅 

I'll get that application process going this week.

**Comment by ianthetechie** [comment]
This is one of the more helpful guides I've seen on the topic: https://www.bitshifted.co/blog/deploy-maven-central-github-actions-step-by-step-guide/.

**Comment by ianthetechie** [comment]
Only took ~19h of work, but I successfully got an unrelated project published under our fresh Maven Central account. You can probably expect a Ferrostar release there early next week.
