### ISSUE TITLE
Navigation not progressing past the first step

### ISSUE THREAD

**Issue by bjtrounson** [stadiamaps/ferrostar#383]
I've encountered an issue when navigating, it won't progress past the first step. 

I found this after successfully parsing map matched routes and tried navigating down it. I've also tried this on fetched routes from within Ferrostar from the getRoutes method and this is also happening on those routes as well.

Not ruling this out but this might be caused from parsing of route objects via expo module records in my RN layer here: [https://github.com/bjtrounson/expo-ferrostar](https://github.com/bjtrounson/expo-ferrostar)

**_The blue dot is the current location_**
![Screenshot_20241202-122245_Madcap Navigation (Development)](https://github.com/user-attachments/assets/54f2d59a-8c28-464c-95c8-ad38d7ab5b30)

**Comment by ianthetechie** [comment]
To help troubleshoot it a bit more efficiently, could you put together a minimal reproducible example repo? Then maybe I could step through to sanity check the different points of the integration. Since it's working for us in the "native" integration, it's _probably_ either a configuration issue (quick sanity check: what step advance mode did you set?) or some "plumbing" not being connected along the way.

I also see the user location puck isn't moving... Out of curiosity, is the puck always stuck there? If so, it seems like maybe the location updates aren't flowing through from the location provider down to the static location manager in the MapLibre layer 🤔

**Comment by bjtrounson** [comment]
I've figure it out, it was just me being an idiot 🤣

>it's probably either a configuration issue (quick sanity check: what step advance mode did you set?)
It was the step advance mode settings. I had thought I had set the defaults in the my expo records which I had obviously not done, silly me.

Thanks for the pointers. I'll close this issue.
